name: stsg-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - statsmodels
  - scikit-learn
  - tqdm
  - pytorch
  - torchvision
  - cudatoolkit
  - tslearn
